// This file is auto-generated by `npm run icons:generate`.
// Do not edit it manually.
import IconAdd1Svg from "../../../assets/icons/svg/add-1.svg";
import IconAddBellNotificationNotificationAlarmAlertBellAddSvg from "../../../assets/icons/svg/add-bell-notification--notification-alarm-alert-bell-add.svg";
import IconAddCircleButtonRemoveCrossAddButtonsPlusCircleMathematicsMathSvg from "../../../assets/icons/svg/add-circle--button-remove-cross-add-buttons-plus-circle-+-mathematics-math.svg";
import IconAddLayer2LayerAddDesignPlusLayersSquareBoxSvg from "../../../assets/icons/svg/add-layer-2--layer-add-design-plus-layers-square-box.svg";

export const appIcons = {
  "add-1": IconAdd1Svg,
  "add-bell-notification-notification-alarm-alert-bell-add": IconAddBellNotificationNotificationAlarmAlertBellAddSvg,
  "add-circle-button-remove-cross-add-buttons-plus-circle-mathematics-math": IconAddCircleButtonRemoveCrossAddButtonsPlusCircleMathematicsMathSvg,
  "add-layer-2-layer-add-design-plus-layers-square-box": IconAddLayer2LayerAddDesignPlusLayersSquareBoxSvg,
} as const;

export type AppIconName = keyof typeof appIcons;
