// This file is auto-generated by `npm run icons:generate`.
// Do not edit it manually.
import IconAdd1Svg from '../../../assets/icons/svg/add-1.svg';
import IconFindGeoSvg from '../../../assets/icons/svg/find-geo.svg';
import IconMarkerSvg from '../../../assets/icons/svg/marker.svg';
import IconMinusSvg from '../../../assets/icons/svg/minus.svg';
import IconPlusSvg from '../../../assets/icons/svg/plus.svg';

export const appIcons = {
  'add-1': IconAdd1Svg,
  'find-geo': IconFindGeoSvg,
  marker: IconMarkerSvg,
  minus: IconMinusSvg,
  plus: IconPlusSvg,
} as const;

export type AppIconName = keyof typeof appIcons;
